foundation: OpenAPI
url: https://oai.landscape2.io
categories:
  - name: OpenAPI Initiative Members
    subcategories:
      - General
      - Associate
colors:
  color1: rgba(87, 128, 0, 1)
  color2: rgba(22, 128, 115, 1)
  color3: rgba(76, 91, 49, 1)
  color4: rgba(87, 128, 0, 0.9)
  color5: rgba(94, 93, 95, 1)
  color6: rgba(87, 128, 0, 1)
  color7: rgba(252, 255, 246, 1)
footer:
  links:
    github: https://github.com/oai
    homepage: https://openapis.org
    linkedin: https://www.linkedin.com/company/open-api-initiative/
    slack: https://slack.openapis.org/
    twitter: https://twitter.com/OpenApiSpec
    youtube: https://www.youtube.com/@OpenApi
  logo: https://raw.githubusercontent.com/OAI/landscape/refs/heads/main/img/OpenAPI_Logo_White.svg
  text: >
    Copyright © 2024 The Linux Foundation®. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of
    The Linux Foundation, please see our [Trademark Usage page](https://www.linuxfoundation.org/trademark-usage). Linux is a registered trademark of Linus
    Torvalds. [Privacy Policy](https://www.linuxfoundation.org/privacy) and [Terms of Use](https://www.linuxfoundation.org/terms). This website contains data
    received from Crunchbase. This data is not licensed pursuant to the Apache License. It is subject to Crunchbase's Data Access Terms, available at
    <https://data.crunchbase.com/docs/terms>, and is only permitted to be used with Linux Foundation landscape projects.
grid_items_size: large
header:
  links:
    github: https://github.com/OAI/landscape
  logo: https://raw.githubusercontent.com/OAI/landscape/refs/heads/main/img/OpenAPI_Logo_Pantone.svg
images:
  favicon: https://www.openapis.org/wp-content/uploads/sites/3/2016/11/favicon.png
  open_graph: https://www.openapis.org/wp-content/uploads/sites/3/2019/06/favicon-300x300.png
members_category: OpenAPI Initiative Members
screenshot_width: 1500
