# Landscape2 settings
#
# This settings file allows customizing some aspects of the landscape.
#
# Reference documentation: https://github.com/cncf/landscape2/blob/main/docs/config/settings.yml

foundation: OpenAPI

url: http://127.0.0.1:8000

colors:
  color1: "rgba(0, 107, 204, 1)"
  color2: "rgba(255, 0, 170, 1)"
  color3: "rgba(96, 149, 214, 1)"
  color4: "rgba(0, 42, 81, 0.7)"
  color5: "rgba(1, 107, 204, 0.7)"
  color6: "rgba(0, 42, 81, 0.7)"
  color7: "rgba(180, 219, 255, 1)"

featured_items:
  - field: maturity
    options:
      - value: graduated
        order: 1
        label: Graduated

footer:
  links:
    github: "https://github.com/oai"
    homepage: "https://openapis.org"
    linkedin: "https://www.linkedin.com/company/open-api-initiative/"
    slack: "https://slack.openapis.org/"
    twitter: "https://twitter.com/OpenApiSpec"
    youtube: "https://www.youtube.com/@OpenApi"
  logo: "https://raw.githubusercontent.com/OAI/landscape/refs/heads/main/img/OpenAPI_Logo_White.svg"

grid_items_size: large


header:
  links:
    github: "https://github.com/OAI/landscape"
  logo: "https://raw.githubusercontent.com/OAI/landscape/refs/heads/main/img/OpenAPI_Logo_Pantone.svg"

screenshot_width: 1500
